print('Hello world')
print('What is your name?')
myName = input()
print(' It is good to meet you, ' + myName)
print('The lenght of your name is:')
print(len(myName))
print('What is your age?')
MyAge = input()
print('You will be ' + str(int(MyAge) + 1) + ' in a year.')
